error: [autil_vec_ref] Index out of bounds (1)
